// d:\_Code\Flutter\testerx2\lib\presentation\auth\register.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:

export 'bloc/bloc.dart';
export 'view/view.dart';
