// d:\_Code\Flutter\testerx2\lib\presentation\auth\forget_password\view.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:


export 'forget_password_screen.dart';