// d:\_Code\Flutter\testerx2\lib\presentation\new_home\view.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:


export 'new_home_screen.dart';