// d:\_Code\Flutter\testerx2\lib\presentation\settings\view.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:


export 'settings_screen.dart';