// d:\_Code\Flutter\testerx2\lib\presentation\auth\register\bloc.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:


export 'register_bloc.dart';