// d:\_Code\Flutter\testerx2\lib\presentation\history\view.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:


export 'history_screen.dart';
export 'index.dart';