// d:\_Code\Flutter\testerx2\lib\presentation\main\view.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:


export 'index.dart';
export 'main_screen.dart';