// d:\_Code\Flutter\testerx2\lib\presentation\main.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:

export 'view/view.dart';
export 'widgets/widgets.dart';
