// d:\_Code\Flutter\testerx2\lib\presentation\auth\register\view.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:


export 'index.dart';
export 'register_screen.dart';