// d:\_Code\Flutter\testerx2\lib\presentation\auth\login\view.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:

export 'login_screen.dart';
